# Generated by Django 2.2.7 on 2019-12-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20191223_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banners',
            new_name='Banners_details',
        ),
    ]
