# Generated by Django 2.2.7 on 2019-12-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_auto_20191223_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners_details',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
