# Generated by Django 2.2.7 on 2019-12-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_auto_20191223_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners_details',
            name='name',
        ),
    ]
