# Generated by Django 2.2.7 on 2019-12-24 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_banners_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners_details',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
